[general]
import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

live_config_reload = true
working_directory = "None"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.92

[window.padding]
x = 20
y = 20

[font]
size = 14
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 1 }
normal = { family = "JetBrainsMono NFP Light" }
bold = { family = "JetBrainsMono NFP Light" }
italic = { family = "JetBrainsMono NFP Light" }
bold_italic = { family = "JetBrainsMono NFP Light" }

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
