[general]
live_config_reload = true
working_directory = "None"
import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window]
padding = { x = 10, y = 10 }

[font]
size = 14
normal = { family = "0xProto Nerd Font Propo" }
bold = { family = "0xProto Nerd Font Propo" }
italic = { family = "0xProto Nerd Font Propo" }
bold_italic = { family = "0xProto Nerd Font Propo" }

[cursor]
unfocused_hollow = true
style = { blinking = "On", shape = "Block" }
vi_mode_style = { blinking = "On", shape = "Block" }

[selection]
save_to_clipboard = true
