[general]
live_config_reload = true
working_directory = "None"
import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
# opacity = 

[font]
size = 14
normal = { family = "JetBrains Mono NF" }
bold = { family = "JetBrains Mono NF" }
italic = { family = "JetBrains Mono NF" }
bold_italic = { family = "JetBrains Mono NF" }

[cursor]
unfocused_hollow = true
style = { blinking = "Off", shape = "Block" }
vi_mode_style = { blinking = "Off", shape = "Block" }

[selection]
save_to_clipboard = true
