[env]
TERM = "xterm-256color"

[general]
live_config_reload = true
working_directory = "None"
import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window]
padding = { x = 20, y = 20 }

[font]
size = 15
normal = { family = "FiraCode Nerd Font Propo" }
bold = { family = "FiraCode Nerd Font Propo" }
italic = { family = "FiraCode Nerd Font Propo" }
bold_italic = { family = "FiraCode Nerd Font Propo" }

[cursor]
unfocused_hollow = true
style = { blinking = "On", shape = "Block" }
vi_mode_style = { blinking = "On", shape = "Block" }

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
